# Generated by Django 4.2.1 on 2023-11-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0008_wife_men_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='wife',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband', to='men.wife'),
        ),
    ]
