# Generated by Django 4.2.1 on 2023-11-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0009_alter_men_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
